# Ref: https://openapi-generator.tech/docs/generators/swift5/

projectName: Traq
swiftUseApiNamespace: true
removeMigrationProjectNameClass: true
responseAs: Result,AsyncAwait
useSPMFileStructure: true
