name: Traq
targets:
  Traq:
    type: framework
    platform: iOS
    deploymentTarget: "9.0"
    sources: [Traq]
    info:
      path: ./Info.plist
      version: 3.0
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: AnyCodable
