//
// BotState.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

@available(*, deprecated, renamed: "TraqAPI.BotState")
public typealias BotState = TraqAPI.BotState

public extension TraqAPI {
    /** BOT状態 0: 停止 1: 有効 2: 一時停止 */
    enum BotState: Int, Codable, CaseIterable {
        case deactivated = 0
        case active = 1
        case suspended = 2
    }
}
