//
// PutMyPasswordRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

@available(*, deprecated, renamed: "TraqAPI.PutMyPasswordRequest")
public typealias PutMyPasswordRequest = TraqAPI.PutMyPasswordRequest

public extension TraqAPI {
    /** パスワード変更リクエスト */
    struct PutMyPasswordRequest: Codable, JSONEncodable, Hashable {
        /** 現在のパスワード */
        public var password: String
        /** 新しいパスワード */
        public var newPassword: String

        public init(password: String, newPassword: String) {
            self.password = password
            self.newPassword = newPassword
        }

        public enum CodingKeys: String, CodingKey, CaseIterable {
            case password
            case newPassword
        }

        // Encodable protocol methods

        public func encode(to encoder: Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(password, forKey: .password)
            try container.encode(newPassword, forKey: .newPassword)
        }
    }
}
