//
// ThumbnailType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

@available(*, deprecated, renamed: "TraqAPI.ThumbnailType")
public typealias ThumbnailType = TraqAPI.ThumbnailType

public extension TraqAPI {
    /** サムネイル画像のタイプ  */
    enum ThumbnailType: String, Codable, CaseIterable {
        case image
        case waveform
    }
}
