//
// UserSettings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

@available(*, deprecated, renamed: "TraqAPI.UserSettings")
public typealias UserSettings = TraqAPI.UserSettings

public extension TraqAPI {
    /** ユーザー設定の情報 */
    struct UserSettings: Codable, JSONEncodable, Hashable {
        /** ユーザーUUID */
        public var id: UUID
        /** メッセージ引用通知の設定情報 */
        public var notifyCitation: Bool

        public init(id: UUID, notifyCitation: Bool) {
            self.id = id
            self.notifyCitation = notifyCitation
        }

        public enum CodingKeys: String, CodingKey, CaseIterable {
            case id
            case notifyCitation
        }

        // Encodable protocol methods

        public func encode(to encoder: Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(id, forKey: .id)
            try container.encode(notifyCitation, forKey: .notifyCitation)
        }
    }
}
