//
// MessageClip.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** メッセージクリップ */
public struct MessageClip: Codable, JSONEncodable, Hashable {

    /** クリップされているフォルダのID */
    public var folderId: UUID
    /** クリップされた日時 */
    public var clippedAt: Date

    public init(folderId: UUID, clippedAt: Date) {
        self.folderId = folderId
        self.clippedAt = clippedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case folderId
        case clippedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(folderId, forKey: .folderId)
        try container.encode(clippedAt, forKey: .clippedAt)
    }
}

