//
// MessagePin.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** ピン情報 */
public struct MessagePin: Codable, JSONEncodable, Hashable {

    /** ピン留めしたユーザーUUID */
    public var userId: UUID
    /** ピン留めされた日時 */
    public var pinnedAt: Date

    public init(userId: UUID, pinnedAt: Date) {
        self.userId = userId
        self.pinnedAt = pinnedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userId
        case pinnedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(userId, forKey: .userId)
        try container.encode(pinnedAt, forKey: .pinnedAt)
    }
}

