//
// PutChannelTopicRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** チャンネルトピック編集リクエスト */
public struct PutChannelTopicRequest: Codable, JSONEncodable, Hashable {

    /** トピック */
    public var topic: String

    public init(topic: String) {
        self.topic = topic
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case topic
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(topic, forKey: .topic)
    }
}

