//
// PostUnlinkExternalAccount.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

@available(*, deprecated, renamed: "TraqAPI.PostUnlinkExternalAccount")
public typealias PostUnlinkExternalAccount = TraqAPI.PostUnlinkExternalAccount

public extension TraqAPI {
    /** POST /users/me/ex-accounts/unlink 用リクエストボディ */
    struct PostUnlinkExternalAccount: Codable, JSONEncodable, Hashable {
        /** 外部サービス名 */
        public var providerName: String

        public init(providerName: String) {
            self.providerName = providerName
        }

        public enum CodingKeys: String, CodingKey, CaseIterable {
            case providerName
        }

        // Encodable protocol methods

        public func encode(to encoder: Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(providerName, forKey: .providerName)
        }
    }
}
