//
// PutUserPasswordRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "TraqAPI.PutUserPasswordRequest")
public typealias PutUserPasswordRequest = TraqAPI.PutUserPasswordRequest

extension TraqAPI {

/** ユーザーパスワード変更リクエスト */
public struct PutUserPasswordRequest: Codable, JSONEncodable, Hashable {

    /** 新しいパスワード */
    public var newPassword: String

    public init(newPassword: String) {
        self.newPassword = newPassword
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case newPassword
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(newPassword, forKey: .newPassword)
    }
}

}
