//
// ClipAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

extension TraqAPI {
    open class ClipAPI {
        /**
         メッセージをクリップフォルダに追加

         - parameter folderId: (path) クリップフォルダUUID
         - parameter postClipFolderMessageRequest: (body)  (optional)
         - returns: ClippedMessage
         */
        @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
        open class func clipMessage(folderId: UUID, postClipFolderMessageRequest: PostClipFolderMessageRequest? = nil) async throws -> ClippedMessage {
            try await clipMessageWithRequestBuilder(folderId: folderId, postClipFolderMessageRequest: postClipFolderMessageRequest).execute().body
        }

        /**
         メッセージをクリップフォルダに追加
         - POST /clip-folders/{folderId}/messages
         - 指定したメッセージを指定したクリップフォルダに追加します。
         - OAuth:
           - type: oauth2
           - name: OAuth2
         - Bearer Token:
           - type: http
           - name: bearerAuth
         - parameter folderId: (path) クリップフォルダUUID
         - parameter postClipFolderMessageRequest: (body)  (optional)
         - returns: RequestBuilder<ClippedMessage>
         */
        open class func clipMessageWithRequestBuilder(folderId: UUID, postClipFolderMessageRequest: PostClipFolderMessageRequest? = nil) -> RequestBuilder<ClippedMessage> {
            var localVariablePath = "/clip-folders/{folderId}/messages"
            let folderIdPreEscape = "\(APIHelper.mapValueToPathItem(folderId))"
            let folderIdPostEscape = folderIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            localVariablePath = localVariablePath.replacingOccurrences(of: "{folderId}", with: folderIdPostEscape, options: .literal, range: nil)
            let localVariableURLString = TraqAPI.basePath + localVariablePath
            let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: postClipFolderMessageRequest)

            let localVariableUrlComponents = URLComponents(string: localVariableURLString)

            let localVariableNillableHeaders: [String: Any?] = [:]

            let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

            let localVariableRequestBuilder: RequestBuilder<ClippedMessage>.Type = TraqAPI.requestBuilderFactory.getBuilder()

            return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
        }

        /**
         クリップフォルダを作成

         - parameter postClipFolderRequest: (body)  (optional)
         - returns: ClipFolder
         */
        @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
        open class func createClipFolder(postClipFolderRequest: PostClipFolderRequest? = nil) async throws -> ClipFolder {
            try await createClipFolderWithRequestBuilder(postClipFolderRequest: postClipFolderRequest).execute().body
        }

        /**
         クリップフォルダを作成
         - POST /clip-folders
         - クリップフォルダを作成します。 既にあるフォルダと同名のフォルダを作成することは可能です。
         - OAuth:
           - type: oauth2
           - name: OAuth2
         - Bearer Token:
           - type: http
           - name: bearerAuth
         - parameter postClipFolderRequest: (body)  (optional)
         - returns: RequestBuilder<ClipFolder>
         */
        open class func createClipFolderWithRequestBuilder(postClipFolderRequest: PostClipFolderRequest? = nil) -> RequestBuilder<ClipFolder> {
            let localVariablePath = "/clip-folders"
            let localVariableURLString = TraqAPI.basePath + localVariablePath
            let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: postClipFolderRequest)

            let localVariableUrlComponents = URLComponents(string: localVariableURLString)

            let localVariableNillableHeaders: [String: Any?] = [:]

            let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

            let localVariableRequestBuilder: RequestBuilder<ClipFolder>.Type = TraqAPI.requestBuilderFactory.getBuilder()

            return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
        }

        /**
         クリップフォルダを削除

         - parameter folderId: (path) クリップフォルダUUID
         - returns: Void
         */
        @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
        open class func deleteClipFolder(folderId: UUID) async throws {
            try await deleteClipFolderWithRequestBuilder(folderId: folderId).execute().body
        }

        /**
         クリップフォルダを削除
         - DELETE /clip-folders/{folderId}
         - 指定したクリップフォルダを削除します。
         - OAuth:
           - type: oauth2
           - name: OAuth2
         - Bearer Token:
           - type: http
           - name: bearerAuth
         - parameter folderId: (path) クリップフォルダUUID
         - returns: RequestBuilder<Void>
         */
        open class func deleteClipFolderWithRequestBuilder(folderId: UUID) -> RequestBuilder<Void> {
            var localVariablePath = "/clip-folders/{folderId}"
            let folderIdPreEscape = "\(APIHelper.mapValueToPathItem(folderId))"
            let folderIdPostEscape = folderIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            localVariablePath = localVariablePath.replacingOccurrences(of: "{folderId}", with: folderIdPostEscape, options: .literal, range: nil)
            let localVariableURLString = TraqAPI.basePath + localVariablePath
            let localVariableParameters: [String: Any]? = nil

            let localVariableUrlComponents = URLComponents(string: localVariableURLString)

            let localVariableNillableHeaders: [String: Any?] = [:]

            let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

            let localVariableRequestBuilder: RequestBuilder<Void>.Type = TraqAPI.requestBuilderFactory.getNonDecodableBuilder()

            return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
        }

        /**
         クリップフォルダ情報を編集

         - parameter folderId: (path) クリップフォルダUUID
         - parameter patchClipFolderRequest: (body)  (optional)
         - returns: Void
         */
        @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
        open class func editClipFolder(folderId: UUID, patchClipFolderRequest: PatchClipFolderRequest? = nil) async throws {
            try await editClipFolderWithRequestBuilder(folderId: folderId, patchClipFolderRequest: patchClipFolderRequest).execute().body
        }

        /**
         クリップフォルダ情報を編集
         - PATCH /clip-folders/{folderId}
         - 指定したクリップフォルダの情報を編集します。
         - OAuth:
           - type: oauth2
           - name: OAuth2
         - Bearer Token:
           - type: http
           - name: bearerAuth
         - parameter folderId: (path) クリップフォルダUUID
         - parameter patchClipFolderRequest: (body)  (optional)
         - returns: RequestBuilder<Void>
         */
        open class func editClipFolderWithRequestBuilder(folderId: UUID, patchClipFolderRequest: PatchClipFolderRequest? = nil) -> RequestBuilder<Void> {
            var localVariablePath = "/clip-folders/{folderId}"
            let folderIdPreEscape = "\(APIHelper.mapValueToPathItem(folderId))"
            let folderIdPostEscape = folderIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            localVariablePath = localVariablePath.replacingOccurrences(of: "{folderId}", with: folderIdPostEscape, options: .literal, range: nil)
            let localVariableURLString = TraqAPI.basePath + localVariablePath
            let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: patchClipFolderRequest)

            let localVariableUrlComponents = URLComponents(string: localVariableURLString)

            let localVariableNillableHeaders: [String: Any?] = [:]

            let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

            let localVariableRequestBuilder: RequestBuilder<Void>.Type = TraqAPI.requestBuilderFactory.getNonDecodableBuilder()

            return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
        }

        /**
         クリップフォルダ情報を取得

         - parameter folderId: (path) クリップフォルダUUID
         - returns: ClipFolder
         */
        @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
        open class func getClipFolder(folderId: UUID) async throws -> ClipFolder {
            try await getClipFolderWithRequestBuilder(folderId: folderId).execute().body
        }

        /**
         クリップフォルダ情報を取得
         - GET /clip-folders/{folderId}
         - 指定したクリップフォルダの情報を取得します。
         - OAuth:
           - type: oauth2
           - name: OAuth2
         - Bearer Token:
           - type: http
           - name: bearerAuth
         - parameter folderId: (path) クリップフォルダUUID
         - returns: RequestBuilder<ClipFolder>
         */
        open class func getClipFolderWithRequestBuilder(folderId: UUID) -> RequestBuilder<ClipFolder> {
            var localVariablePath = "/clip-folders/{folderId}"
            let folderIdPreEscape = "\(APIHelper.mapValueToPathItem(folderId))"
            let folderIdPostEscape = folderIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            localVariablePath = localVariablePath.replacingOccurrences(of: "{folderId}", with: folderIdPostEscape, options: .literal, range: nil)
            let localVariableURLString = TraqAPI.basePath + localVariablePath
            let localVariableParameters: [String: Any]? = nil

            let localVariableUrlComponents = URLComponents(string: localVariableURLString)

            let localVariableNillableHeaders: [String: Any?] = [:]

            let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

            let localVariableRequestBuilder: RequestBuilder<ClipFolder>.Type = TraqAPI.requestBuilderFactory.getBuilder()

            return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
        }

        /**
         クリップフォルダのリストを取得

         - returns: [ClipFolder]
         */
        @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
        open class func getClipFolders() async throws -> [ClipFolder] {
            try await getClipFoldersWithRequestBuilder().execute().body
        }

        /**
         クリップフォルダのリストを取得
         - GET /clip-folders
         - 自身が所有するクリップフォルダのリストを取得します。
         - OAuth:
           - type: oauth2
           - name: OAuth2
         - Bearer Token:
           - type: http
           - name: bearerAuth
         - returns: RequestBuilder<[ClipFolder]>
         */
        open class func getClipFoldersWithRequestBuilder() -> RequestBuilder<[ClipFolder]> {
            let localVariablePath = "/clip-folders"
            let localVariableURLString = TraqAPI.basePath + localVariablePath
            let localVariableParameters: [String: Any]? = nil

            let localVariableUrlComponents = URLComponents(string: localVariableURLString)

            let localVariableNillableHeaders: [String: Any?] = [:]

            let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

            let localVariableRequestBuilder: RequestBuilder<[ClipFolder]>.Type = TraqAPI.requestBuilderFactory.getBuilder()

            return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
        }

        /**
         * enum for parameter order
         */
        public enum Order_getClips: String, CaseIterable {
            case asc
            case desc
        }

        /**
         フォルダ内のクリップのリストを取得

         - parameter folderId: (path) クリップフォルダUUID
         - parameter limit: (query) 取得する件数 (optional)
         - parameter offset: (query) 取得するオフセット (optional, default to 0)
         - parameter order: (query) 昇順か降順か (optional, default to .desc)
         - returns: [ClippedMessage]
         */
        @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
        open class func getClips(folderId: UUID, limit: Int? = nil, offset: Int? = nil, order: Order_getClips? = nil) async throws -> [ClippedMessage] {
            try await getClipsWithRequestBuilder(folderId: folderId, limit: limit, offset: offset, order: order).execute().body
        }

        /**
         フォルダ内のクリップのリストを取得
         - GET /clip-folders/{folderId}/messages
         - 指定したフォルダ内のクリップのリストを取得します。 `order`を指定しない場合、クリップした日時の新しい順で返されます。
         - OAuth:
           - type: oauth2
           - name: OAuth2
         - Bearer Token:
           - type: http
           - name: bearerAuth
         - parameter folderId: (path) クリップフォルダUUID
         - parameter limit: (query) 取得する件数 (optional)
         - parameter offset: (query) 取得するオフセット (optional, default to 0)
         - parameter order: (query) 昇順か降順か (optional, default to .desc)
         - returns: RequestBuilder<[ClippedMessage]>
         */
        open class func getClipsWithRequestBuilder(folderId: UUID, limit: Int? = nil, offset: Int? = nil, order: Order_getClips? = nil) -> RequestBuilder<[ClippedMessage]> {
            var localVariablePath = "/clip-folders/{folderId}/messages"
            let folderIdPreEscape = "\(APIHelper.mapValueToPathItem(folderId))"
            let folderIdPostEscape = folderIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            localVariablePath = localVariablePath.replacingOccurrences(of: "{folderId}", with: folderIdPostEscape, options: .literal, range: nil)
            let localVariableURLString = TraqAPI.basePath + localVariablePath
            let localVariableParameters: [String: Any]? = nil

            var localVariableUrlComponents = URLComponents(string: localVariableURLString)
            localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
                "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
                "offset": (wrappedValue: offset?.encodeToJSON(), isExplode: true),
                "order": (wrappedValue: order?.encodeToJSON(), isExplode: true),
            ])

            let localVariableNillableHeaders: [String: Any?] = [:]

            let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

            let localVariableRequestBuilder: RequestBuilder<[ClippedMessage]>.Type = TraqAPI.requestBuilderFactory.getBuilder()

            return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
        }

        /**
         自分のクリップを取得

         - parameter messageId: (path) メッセージUUID
         - returns: [MessageClip]
         */
        @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
        open class func getMessageClips(messageId: UUID) async throws -> [MessageClip] {
            try await getMessageClipsWithRequestBuilder(messageId: messageId).execute().body
        }

        /**
         自分のクリップを取得
         - GET /messages/{messageId}/clips
         - 対象のメッセージの自分のクリップの一覧を返します。
         - OAuth:
           - type: oauth2
           - name: OAuth2
         - Bearer Token:
           - type: http
           - name: bearerAuth
         - parameter messageId: (path) メッセージUUID
         - returns: RequestBuilder<[MessageClip]>
         */
        open class func getMessageClipsWithRequestBuilder(messageId: UUID) -> RequestBuilder<[MessageClip]> {
            var localVariablePath = "/messages/{messageId}/clips"
            let messageIdPreEscape = "\(APIHelper.mapValueToPathItem(messageId))"
            let messageIdPostEscape = messageIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            localVariablePath = localVariablePath.replacingOccurrences(of: "{messageId}", with: messageIdPostEscape, options: .literal, range: nil)
            let localVariableURLString = TraqAPI.basePath + localVariablePath
            let localVariableParameters: [String: Any]? = nil

            let localVariableUrlComponents = URLComponents(string: localVariableURLString)

            let localVariableNillableHeaders: [String: Any?] = [:]

            let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

            let localVariableRequestBuilder: RequestBuilder<[MessageClip]>.Type = TraqAPI.requestBuilderFactory.getBuilder()

            return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
        }

        /**
         メッセージをクリップフォルダから除外

         - parameter folderId: (path) クリップフォルダUUID
         - parameter messageId: (path) メッセージUUID
         - returns: Void
         */
        @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
        open class func unclipMessage(folderId: UUID, messageId: UUID) async throws {
            try await unclipMessageWithRequestBuilder(folderId: folderId, messageId: messageId).execute().body
        }

        /**
         メッセージをクリップフォルダから除外
         - DELETE /clip-folders/{folderId}/messages/{messageId}
         - 指定したフォルダから指定したメッセージのクリップを除外します。 既に外されているメッセージを指定した場合は204を返します。
         - OAuth:
           - type: oauth2
           - name: OAuth2
         - Bearer Token:
           - type: http
           - name: bearerAuth
         - parameter folderId: (path) クリップフォルダUUID
         - parameter messageId: (path) メッセージUUID
         - returns: RequestBuilder<Void>
         */
        open class func unclipMessageWithRequestBuilder(folderId: UUID, messageId: UUID) -> RequestBuilder<Void> {
            var localVariablePath = "/clip-folders/{folderId}/messages/{messageId}"
            let folderIdPreEscape = "\(APIHelper.mapValueToPathItem(folderId))"
            let folderIdPostEscape = folderIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            localVariablePath = localVariablePath.replacingOccurrences(of: "{folderId}", with: folderIdPostEscape, options: .literal, range: nil)
            let messageIdPreEscape = "\(APIHelper.mapValueToPathItem(messageId))"
            let messageIdPostEscape = messageIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
            localVariablePath = localVariablePath.replacingOccurrences(of: "{messageId}", with: messageIdPostEscape, options: .literal, range: nil)
            let localVariableURLString = TraqAPI.basePath + localVariablePath
            let localVariableParameters: [String: Any]? = nil

            let localVariableUrlComponents = URLComponents(string: localVariableURLString)

            let localVariableNillableHeaders: [String: Any?] = [:]

            let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

            let localVariableRequestBuilder: RequestBuilder<Void>.Type = TraqAPI.requestBuilderFactory.getNonDecodableBuilder()

            return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
        }
    }
}
