//
// WebrtcAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

extension TraqAPI {
    open class WebrtcAPI {
        /**
         WebRTC状態を取得

         - returns: [WebRTCUserState]
         */
        @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
        open class func getWebRTCState() async throws -> [WebRTCUserState] {
            try await getWebRTCStateWithRequestBuilder().execute().body
        }

        /**
         WebRTC状態を取得
         - GET /webrtc/state
         - 現在のWebRTC状態を取得します。
         - OAuth:
           - type: oauth2
           - name: OAuth2
         - Bearer Token:
           - type: http
           - name: bearerAuth
         - returns: RequestBuilder<[WebRTCUserState]>
         */
        open class func getWebRTCStateWithRequestBuilder() -> RequestBuilder<[WebRTCUserState]> {
            let localVariablePath = "/webrtc/state"
            let localVariableURLString = TraqAPI.basePath + localVariablePath
            let localVariableParameters: [String: Any]? = nil

            let localVariableUrlComponents = URLComponents(string: localVariableURLString)

            let localVariableNillableHeaders: [String: Any?] = [:]

            let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

            let localVariableRequestBuilder: RequestBuilder<[WebRTCUserState]>.Type = TraqAPI.requestBuilderFactory.getBuilder()

            return localVariableRequestBuilder.init(method: "GET", URLString: localVariableUrlComponents?.string ?? localVariableURLString, parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
        }

        /**
         Skyway用認証API

         - parameter postWebRTCAuthenticateRequest: (body)  (optional)
         - returns: WebRTCAuthenticateResult
         */
        @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
        open class func postWebRTCAuthenticate(postWebRTCAuthenticateRequest: PostWebRTCAuthenticateRequest? = nil) async throws -> WebRTCAuthenticateResult {
            try await postWebRTCAuthenticateWithRequestBuilder(postWebRTCAuthenticateRequest: postWebRTCAuthenticateRequest).execute().body
        }

        /**
         Skyway用認証API
         - POST /webrtc/authenticate
         - Skyway WebRTC用の認証API
         - OAuth:
           - type: oauth2
           - name: OAuth2
         - Bearer Token:
           - type: http
           - name: bearerAuth
         - parameter postWebRTCAuthenticateRequest: (body)  (optional)
         - returns: RequestBuilder<WebRTCAuthenticateResult>
         */
        open class func postWebRTCAuthenticateWithRequestBuilder(postWebRTCAuthenticateRequest: PostWebRTCAuthenticateRequest? = nil) -> RequestBuilder<WebRTCAuthenticateResult> {
            let localVariablePath = "/webrtc/authenticate"
            let localVariableURLString = TraqAPI.basePath + localVariablePath
            let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: postWebRTCAuthenticateRequest)

            let localVariableUrlComponents = URLComponents(string: localVariableURLString)

            let localVariableNillableHeaders: [String: Any?] = [:]

            let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

            let localVariableRequestBuilder: RequestBuilder<WebRTCAuthenticateResult>.Type = TraqAPI.requestBuilderFactory.getBuilder()

            return localVariableRequestBuilder.init(method: "POST", URLString: localVariableUrlComponents?.string ?? localVariableURLString, parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
        }
    }
}
